#!/bin/bash

#
# This file is part of the batocera distribution (https://batocera.org).
# Copyright (c) 2025+.
#
# This program is free software: you can redistribute it and/or modify  
# it under the terms of the GNU General Public License as published by  
# the Free Software Foundation, version 3.
#
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# YOU MUST KEEP THIS HEADER AS IT IS
#

# batocera-xtract, a script as universal extractor tool and to mimic file-roller base functions
# MimeTypes=application/x-7z-compressed;application/gzip;application/vnd.rar;application/x-tar;application/x-compressed-tar;
#           application/x-xz-compressed-tar;application/x-xz;application/zip;

# inital idea and inspired by brunoeduardobrasil, 07/19/2025 cyperghost aka crcerror
# ec-codes: ec-0 okay, ec-1 error, ec-10 parameter l used
# ec-11 archives not supported for extraction, ec-12 archives not supported for showing content
# ec-21 to 28 -- file extraction error zip rar 7z gz xy tar tar.xz tar.gz

# Is pcmanfm is active then use yad as output. test -t will not work because pcmanfm creates a virtual terminal
pgrep pcmanfm >/dev/null && TERMINAL=0 || TERMINAL=1
ret=0

list_archive () {
    # We try just to obtain the file names with minimal filters, unzip -Z1, unrar lb, 7zr l -ba ... and some awk/sed tools
    case "$1" in
        *.zip) readarray -t array < <(unzip -Z1 "$FILE") ;;
        *.rar) readarray -t array < <(unrar lb "$FILE") ;;
        *.7z)  readarray -t array < <(7zr l -ba "$FILE" | awk '{$1=$2=$3=$4=""; print $0}' |  sed 's/^[ ]*[0-9]*[ ]//') ;;
        *.tar) readarray -t array < <(tar -tvf "$FILE" | awk '{ for(i=6; i<NF; ++i) printf $i" "; print $NF }') ;;
        *) return 12
    esac

    # Just output for CLI as list - usefull for further scripting
    [[ "${2}" == "l" ]] && { printf '%s\n' "${array[@]}"; return 10; }

    # Rebuild array with a second column to handle files in yad, set to true if you want checkmarks setted
    readarray -t array <<< $(printf 'FALSE\n%s\n' "${array[@]}")

    #Options needs to be added to PCmanFM "file-roller --open"
    readarray -t files <<< $(yad --title="Extract Files" --list --checklist --print-column=2 --separator= --column=Extract:chk --column=Filename:text "${array[@]}" || echo "ABORT" )
    [[ ${#files[@]} -eq 0 || ${files} == "ABORT" ]] && return 1 #Canceld or no file ticked
    return 0
}

extract_archive () {
    case  "$1" in
        # Multiple dotted extensions at first
        *.tar.xz) tar -xJf "$FILE" -C "$DEST" || return 27;;
        *.tar.gz) tar -xzf "$FILE" -C "$DEST" || return 28;;
        # Single dotted extensions later
        *.zip) unzip "$FILE" "${files[@]}" -d "$DEST" || return 21;;
        *.rar) unrar x "$FILE" "${files[@]}" "$DEST/" || return 22;;
        *.7z)  7zr x "$FILE" "${files[@]}" -o"$DEST" || return 23;;
        *.gz)  gunzip -c "$FILE" > "$DEST/$(basename "${FILE%.*}")" || return 24 ;;
        *.xz)  unxz -c "$FILE" > "$DEST/$(basename "${FILE%.*}")" || return 25;;
        *.tar) tar -xf "$FILE" "${files[@]}" -C "$DEST" || return 26;;
        *) return 11
    esac
}

case "$1" in
    x|X) #for CLI as universal extraction tool
        FILE="$2"; DEST="$3"
        [[ -f "$FILE" ]] || { echo "Error! Archive '$FILE' not found"; exit 1; }
        if [[ -z "$DEST" ]]; then
            FILENAME="$(basename "${FILE%.*}")"
            echo "No Destination directory entered!"
            echo "C or 1) to extract to CURRENT: '$PWD'"
            echo "B or 2) to extract to BASEDIR: '$FILENAME' in '$PWD'"
            read -p "Select (C/B) and press Enter: " yn
            case ${yn:0:1} in
                c|C|1) DEST="$PWD" ;;
                b|B|2) mkdir "$FILENAME"; DEST="${PWD}/${FILENAME}" ;;
                *)   echo "...Aborted!"; exit 1
            esac
        fi
        [[ -d "$DEST" ]] && extract_archive "${FILE,,}" || ret=3
    ;;
    --extract)
        FILE="$2"
        DEST=$(yad --title "Choose destination folder" --file --directory) || exit 1
        extract_archive "${FILE,,}" || ret=$?
    ;;
    --extract-to)
        FILE="$3"
        DEST="${2/file:\/\/}"
        extract_archive "${FILE,,}" || ret=$?
    ;;
    --open|open|l|L)
        FILE="$2"
        DEST="$(readlink -f "$(dirname "${FILE}")")"
        list_archive "${FILE,,}" "${1,,}" && extract_archive "${FILE,,}" || ret=$?
    ;;
    --add)
        # We remove $0 and $1, create filename.zip if single dir/file, create subdirname.zip for several files/dirs, we need the work-dir to have the relative pathes
        FILE=("${@:2}")
        DEST="${FILE%/*}"
        [[ -n "${DEST}" ]] && { cd "${DEST}" || { yad --title "Error" --text "Can't open directory '$DEST'"; exit 1; }; } || { DEST="/root"; cd /; }
        [[ ${#FILE[@]} -gt 1 ]] && { DEST="${DEST}/$(basename "${DEST}")"; }
        [[ ${#FILE[@]} -eq 1 ]] && { DEST="$(basename "${FILE%.*}")"; }
        [[ -f "${DEST}.zip" ]] && DEST="${DEST}_$(printf '%x' $(date +%s)).zip" || DEST="${DEST}.zip"
        FILE=("${FILE[@]/*\/}")   #strip pathes to avoid to build archives with absolue pathes
        zip -q -r "$DEST" "${FILE[@]}" && { yad --title "Created zip" --text "Created '$(readlink -f $DEST)' and added ${#FILE[@]} files:\n$(printf '%s\n' "${FILE[@]}")"; exit 0; } || exit 1
    ;;
   *) ret=2
esac

case $ret in
    0|1) true ;;
    2) # Action not defined
        [[ $TERMINAL -eq 0 ]] && { yad --title "Error" --text "Action: '$1' is unknown"; exit 1; }
        echo "Usage: $(basename "$0") <SWITCHES> [ARCHIVEFILE] {DESTINATION-DIR}"; echo
        echo "    x: extraction of current archivfile"
        echo "    l: list archive content"; echo
        echo "Supported archives for extraction: zip 7z rar tar gz xz tar.gz tar.xz"
        echo "Supported archives for list/open : zip 7z rar tar"; echo
        echo "error-codes/return codes:"
        echo "  ec-0 no error, ec-10 parameter 'l', okay -- ec-1 general error -- ec-2 unknown action"
        echo "  ec-11 to 12  -- archive type not supported for extraction, listing"
        echo "  eec-21 to 28 -- file extraction error zip rar 7z gz xy tar tar.xz tar.gz";echo
    ;;
    3)  echo "Error! Destionation directory '$DEST' not found" ;; #CLI Destination dir not found
    11|12) # Extension not supported for extraction or listing
        [[ $TERMINAL -eq 0 ]] && { yad --title "Error" --text "Archive type: '${FILE##*.}' is not yet supported.\nFailed to open '$FILE'"; }
        [[ $TERMINAL -eq 1 ]] && { echo "Error: Archive type: '${FILE##*.}' is not yet supported. Failed to open '$FILE'"; }
    ;;
   2[1-8]) echo "Extraction error for arhive type: $ret" ;;
esac
exit $ret
