#!/bin/bash
# file-roller mimic for BATOCERA 07/19/2025 cyperghost aka crcerror
# inital idea and inspired by brunoeduardobrasil

#MimeTypes=application/x-7z-compressed;application/gzip;application/vnd.rar;application/x-tar;application/x-compressed-tar;
#          application/x-xz-compressed-tar;application/x-xz;application/zip;

case "$1" in
    --extract)
        FILE="$2" 
        DEST=$(yad --title "Choose destination folder" --file --directory)
        [[ -z "$DEST" ]] && exit 1
    ;;
    --extract-to)
        FILE="$3"
        DEST="${2/file:\/\/}"
    ;;
    *) yad --title "Error" --geometry=400x100 --text "Action: '$1' is unknown"
       exit 1
esac

FILENAME="$(basename "$FILE")"
for EXT in tar.gz tar.xz tar gz xz zip rar 7z; do
    [[ "${FILENAME,,}" =~ ^.*\."$EXT"$ ]] && break || EXT=
done
[[ -z "$EXT" ]] && exit 11

case "$EXT" in
    zip) unzip "$FILE" -d "$DEST" ;;
    rar) unrar x "$FILE" "$DEST/" ;;
    7z)  7zr x "$FILE" -o "$DEST/" ;;
    gz)  gunzip -c "$FILE" > "$DEST/${FILENAME%.gz}" ;;
    xz)  unxz -c "$FILE" > "$DEST/${FILENAME%.xz}" ;;
    tar) tar -xf "$FILE" -C "$DEST" ;;
    # Multiple TAR variants
    tar.xz) tar -xJf "$FILE" -C "$DEST" ;;
    tar.gz) tar -xzf "$FILE" -C "$DEST" ;;
esac
